- hosts: servers # installer dit op all hosts onder "servers:
  tasks:
    - name: Create a directory if it does not exist
      become: yes # become is kort voor become_user root
      file:
        path: /ansible_was_here
        state: directory

    - name: Install SL
      become: yes
      apt:
        name: sl
        state: present
        update_cache: yes